<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tameru.Accounts.Api</RootNamespace>
    <AssemblyName>Tameru.Accounts.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tameru.SharedKernel\Tameru.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Tameru.Web.Common\Tameru.Web.Common.csproj" />
    <ProjectReference Include="..\..\..\Modules.Contracts\Tameru.Modules.Contracts.csproj" />
    <ProjectReference Include="..\Tameru.Accounts.Application\Tameru.Accounts.Application.csproj" />
    <ProjectReference Include="..\Tameru.Accounts.Infrastructure\Tameru.Accounts.Infrastructure.csproj" />
    <ProjectReference Include="..\Tameru.Accounts.Domain\Tameru.Accounts.Domain.csproj" />
  </ItemGroup>

</Project>
