namespace Tameru.Reporting.Application.Contracts;

public sealed record SafeToSpendDto(
    decimal LiquidCash,
    decimal UnpaidObligations,
    decimal SafetyBuffer,
    decimal SafeToSpend,
    int DaysRemaining,
    decimal DailyAllowance,
    DateOnly CycleStart,
    DateOnly CycleEnd,
    DateOnly NextPayday,
    IReadOnlyList<ObligationItemDto> UpcomingObligations,
    IReadOnlyList<LiquidAccountDto> LiquidAccounts);

public sealed record LiquidAccountDto(
    Guid Id,
    string Name,
    string Type,
    decimal Balance);

public sealed record ObligationItemDto(
    Guid Id,
    string Name,
    decimal Amount,
    string Section,
    DateOnly? DueDate,
    bool IsDueBeforePayday);

public sealed record SimulatePurchaseRequest(
    decimal Amount,
    Guid? CategoryId = null,
    string? Description = null);

public sealed record SimulatePurchaseResultDto(
    string Verdict, // "Safe", "Warning", "Risky"
    decimal Amount,
    Guid? CategoryId,
    string? CategoryName,
    decimal CurrentSafeToSpend,
    decimal NewSafeToSpend,
    decimal CurrentDailyAllowance,
    decimal NewDailyAllowance,
    int DaysRemaining,
    decimal? CategoryPlan,
    decimal? CategoryActual,
    decimal? CategoryLeftover,
    decimal? CategoryLeftoverAfterPurchase,
    IReadOnlyList<SurplusCategoryDto> SurplusCategories,
    string ImpactSummary);

public sealed record SurplusCategoryDto(
    Guid CategoryId,
    string CategoryName,
    decimal AvailableSurplus);

// --- Proactive Insights -----------------------------------------------------

/// <summary>
/// A single proactive insight generated by analyzing spending patterns, budget pacing,
/// and financial health indicators.
/// </summary>
public sealed record InsightDto(
    string Id,
    string Type,          // "spending_velocity" | "anomaly" | "budget_pacing" | "savings_trend" | "runway" | "payday"
    string Severity,      // "info" | "warning" | "critical"
    string Title,
    string Message,
    string? ActionRoute,
    decimal? Value,
    string? CategoryName,
    DateTimeOffset GeneratedAt);

/// <summary>Request to fetch proactive insights with optional filtering.</summary>
public sealed record InsightsRequest(
    int? MaxResults = null,
    string? MinSeverity = null);
